server {
    listen 5173;

    location /api {
        proxy_pass http://backend:3000;  # proxy to backend container
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;  # critical for React Router
    }
}